### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by Infernogd** [SawBlade21/Song-Trash-Can#2]
[2024-08-15_21-51-08.log](https://github.com/user-attachments/files/16631945/2024-08-15_21-51-08.log)

**Comment by SawBlade21** [comment]
What were you doing when it crashed?

**Comment by InfernoZv** [comment]
https://github.com/user-attachments/assets/206c94b5-40a5-4c41-92c1-3be3e4db281d

**Comment by SawBlade21** [comment]
Fixed
