### ISSUE TITLE
Inconsistent trash can texture

### ISSUE THREAD

**Issue by GDColon** [SawBlade21/Song-Trash-Can#3]
VERY minor nitpick, but the trash can texture used by the mod is not the same as the vanilla one from pre-2.206.

The proper texture is GJ_trashBtn_001, not GJ_resetBtn_001 - that one is significantly lower quality.

![image](https://github.com/user-attachments/assets/f873f3b4-782d-4c44-8a62-8ae44c3ba45d)

**Comment by GDColon** [comment]
Also, the trash can is still present in GD - it's just hidden by default. Maybe you can use that?

![image](https://github.com/user-attachments/assets/3f9c758d-1f82-4fcb-92cb-86bb7ac83acb)

**Comment by SawBlade21** [comment]
I didn't even notice it was the wrong texture, I'll fix that, thanks
I originally tried using RobTop's button, but it's unfinished and had crashes I couldn't fix, so it was easier to just make my own button
